### ISSUE TITLE
Type mismatch in example

### ISSUE THREAD

**Issue by serpent213** [elixir-error-tracker/error-tracker#101]
The Getting Started [context example](https://github.com/elixir-error-tracker/error-tracker/blob/87ff8cb7a9c8d84feb4def31b808fd976688610e/guides/Getting%20Started.md#error-context)
```elixir
ErrorTracker.set_context(%{user_id: conn.assigns.current_user.id})
```
uses a context type of `%{:atom => any()}` while [`error_tracker.ex`](https://github.com/elixir-error-tracker/error-tracker/blob/87ff8cb7a9c8d84feb4def31b808fd976688610e/lib/error_tracker.ex#L68) defines it as
```elixir
  @type context :: %{String.t() => any()}
```

Great project!  💠

**Comment by crbelaus** [comment]
Good catch!
