### ISSUE TITLE
Any place to improve the layout on smaller screens

### ISSUE THREAD

**Issue by pieterclaerhout** [elixir-error-tracker/error-tracker#105]
When looking at the errors on my phone, I've noticed that the views are hardly usable. The text overlaps, the actual error is not shown, … Do you have any plans to improve on this?

# Large screen

<img width="1552" alt="Screenshot 2024-11-06 at 15 21 42" src="https://github.com/user-attachments/assets/f7186335-0304-4022-941c-f9f75b2dcc28">

# Small screen

<img width="612" alt="Screenshot 2024-11-06 at 15 21 31" src="https://github.com/user-attachments/assets/4707a163-3c6d-4ccc-a555-ee1726ef850f">

**Comment by crbelaus** [comment]
Hey @pieterclaerhout

We can definitely improve this.

**Comment by crbelaus** [comment]
This should be fixed in #108
