### ISSUE TITLE
Clarify on the readme “this captures exceptions and then stores them in your database”

### ISSUE THREAD

**Issue by RoyalIcing** [elixir-error-tracker/error-tracker#112]
It wasn’t clear from the readme how this works or what the user experience is. It stores the exceptions in the database via Ecto and gives me a secret route to view them?

**Comment by jaimeiniesta** [comment]
Hey, yes, exceptions are stored in the database and also announced via telemetry. Then you have a web dashboard that you can use to view the exceptions and mark them as resolved, etc., and you can also attach to the telemetry events for example to send email alerts.
