### ISSUE TITLE
/errors page reloads infinitely 

### ISSUE THREAD

**Issue by tjarratt** [elixir-error-tracker/error-tracker#114]
I recently tried to add error-tracker to a project, following the fairly well-written [getting-started guide](https://hexdocs.pm/error_tracker/getting-started.html) and when i navigated to the /errors dashboard, saw that the page was loading over and over. Within a few seconds I easily saw the page reload 100 times.

Here is an example of the contents of the console.error logs
> phx-GAvf7rKlWbanF5kB error: unauthorized live_redirect. Falling back to page request -  
Object { reason: "stale" }
[errors:1514:30386](http://localhost:4000/errors)
phx-GAvf7rKlWbanF5kB socket: disconnect for page nav -  undefined [errors:1514:30386](http://localhost:4000/errors)
phx-GAvf7rKlWbanF5kB destroyed: the child has been removed from the parent -  undefined [errors:1514:30386](http://localhost:4000/errors)
 destroyed: the child has been removed from the parent -  undefined

![image](https://github.com/user-attachments/assets/c8a13141-04b6-4a8c-8519-b95e6afa55df)

I scoured the existing error reports and pull requests and didn't see any references to this. Any ideas as to what might be causing this ?

**Comment by crbelaus** [comment]
Interesting. I've never seen this problem before.

Can you provide the backend logs? It would be very helpful to understand what is going on and if it is a backend or frontend issue.

**Comment by tjarratt** [comment]
I think I might know the actual fix for this. The documentation is a bit misleading -- we need to wrap the call to `error_tracker_dashboard/1` in a scope and add an appropriate pipeline.

```elixir
  scope "/error_tracker" do
    pipe_through([:browser, :csrf_protection, :appropriate_authentication])

    error_tracker_dashboard("/")
  end
```

This seemed to fix it for me. I'm going to have a closer look, but assuming this fixes the issue and is expected, I'll gladly write a PR tonight to improve the docs.

**Comment by gorghoa** [comment]
thanks @tjarratt , of course :facepalm:…

Yup wrapping within a scope with csrf prodection fixed it! 

Thank you for your **ultra fast** answers, you rock!
