### ISSUE TITLE
Searching errors through the dashboard using SQLite results in Ecto.QueryError 

### ISSUE THREAD

**Issue by toberoni** [elixir-error-tracker/error-tracker#50]
Searching through the web dashboard doesn't work because SQLite (and other DBs) doesn't support Postgres' ILIKE:

```elixir
ilike is not supported by SQLite3 in query:

from e0 in ErrorTracker.Error,
  where: ilike(e0.reason, ^...),
  select: count()
```
A possible solution would be to change the private filter function `lib/error_tracker/web/live/dashboard.ex` depending on the DB. ILIKE for Postgres and LIKE for other DBs (which search case-insensitive by default). 

```elixir
  defp do_filter({field, value}, query) do
    # conditional filter based on DB?
    where(query, [error], ilike(field(error, ^field), ^"%#{value}%"))
  end
```

**Comment by crbelaus** [comment]
Thanks for the detailed report @toberoni. This should be fixed in #51. We will push a new release once the fix is merged. In the meanwhile you can point your application dependency directly to the branch.

```elixir
mix deps do
  [
    {:error_tracker, "~> 0.2", github: "elixir-error-tracker/error-tracker", branch: "fix-sqlite-search"}
  ]
end

```
