### ISSUE TITLE
make the landing page configurable 

### ISSUE THREAD

**Issue by zimakki** [elixir-error-tracker/error-tracker#55]
Every time I land on the dashboard page I have to click on the resolved/unresolved dropdown... It would be amazing to be able to config the default view to default to only showing the unresolved errors. 

I know you can do it via a url like so `?status=unresolved` but I often find myself typing in the url.

**Comment by crbelaus** [comment]
The dashboard shows all errors by default. This was a deliberate decision and is consistent with other error trackers such as AppSignal and Sentry. Adding configuration for this is out of the question as it would result in extra complexity that we want to avoid.

You can always apply the desired filters and then bookmark the resulting page so you can return back to it right away.
