### ISSUE TITLE
Cannot get migration working

### ISSUE THREAD

**Issue by grahac** [elixir-error-tracker/error-tracker#57]
Ignore!  User error.

**Comment by crbelaus** [comment]
You are defining functions within functions, the `def change do` has to be removed. It should be like this:

```elixir
defmodule <myapp>.Repo.Migrations.AddErrorTracker do
  use Ecto.Migration

  def up, do: ErrorTracker.Migration.up()
  def down, do: ErrorTracker.Migration.down()
end
```

**Comment by grahac** [comment]
Yeah. Just saw that!  I feel a bit foolish here haha

**Comment by crbelaus** [comment]
> Yeah. Just saw that! I feel a bit foolish here haha

No worries!

**Comment by grahac** [comment]
I need more coffee this morning ;)

**Comment by grahac** [comment]
Thanks for the super fast reply though!
