### ISSUE TITLE
Support CSP properly

### ISSUE THREAD

**Issue by gernotkogler** [elixir-error-tracker/error-tracker#58]
If you configure `default-src 'self' data:;` for `content-security-policy`, error_tracker does not work and does not apply the css. In order to make it work, you have to add `style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline';` to you csp config.

[unsafe-inline](https://content-security-policy.com/unsafe-inline/) is not an option that you want in your csp.

**Comment by crbelaus** [comment]
We may need to support the `csp_nonce_assign_key` just like [Oban Web](https://getoban.pro/docs/web/2.10.5/Oban.Web.Router.html#module-content-security-policy) and [Phoenix LiveDashboard](https://hexdocs.pm/phoenix_live_dashboard/Phoenix.LiveDashboard.Router.html#live_dashboard/2) do.

**Comment by crbelaus** [comment]
@gernotkogler this should be fixed on #61, which implements `csp_nonce_assign_key` as an option when mounting the dashboard.

**Comment by odarriba** [comment]
The change is in `main`branch right now and will be included in next release @gernotkogler

**Comment by gernotkogler** [comment]
Very cool 💪
