### ISSUE TITLE
Delete or prune errors

### ISSUE THREAD

**Issue by jaimeiniesta** [elixir-error-tracker/error-tracker#64]
I'm unsure if that's already on your roadmap, but it would be great to have the option to:

* delete errors manually
* have errors being deleted automatically based on a pruning configuration (age and status)

**Comment by crbelaus** [comment]
This is definitely on the roadmap!

**Comment by pmareke** [comment]
Hi @crbelaus do you think I can give it a try?

Taking a look to the code I think I can a new endpoint inside the macro `error_tracker_dashboard`

```elixir
      scope path, alias: false, as: false do
        import Phoenix.LiveView.Router, only: [live: 4, live_session: 3]

        live_session session_name, session_opts do
          live "/", ErrorTracker.Web.Live.Dashboard, :index, as: session_name
          live "/:id", ErrorTracker.Web.Live.Show, :show, as: session_name
          live "/:id/, ErrorTracker.Web.Live.Delete, :delete, as: session_name
          live "/:id/:occurrence_id", ErrorTracker.Web.Live.Show, :show, as: session_name
        end
      end

```

And implement the `ErrorTracker.Web.Live.Delete` module inside the `error_tracker/web/live` directory.

What do you think? I'm really new to Elixir/Phoenix and I would love to help with something easy.
