### ISSUE TITLE
Missing exceptions raised in LiveComponents

### ISSUE THREAD

**Issue by numso** [elixir-error-tracker/error-tracker#73]
I recently noticed a couple of exceptions in my app's logs that aren't showing up in ErrorTracker. I suspect it is because these exceptions originate from a LiveComponent.

The LiveView Telemetry documentation mentions that they also emit these telemetry events for components:

```
[:phoenix, :live_component, :update, :start]
[:phoenix, :live_component, :update, :exception]
[:phoenix, :live_component, :handle_event, :start]
[:phoenix, :live_component, :handle_event, :exception]
```

Looks like this project is missing those and only subscribes to `[:phoenix, :live_view, *]` events:

https://github.com/elixir-error-tracker/error-tracker/blob/720470ca5f32db6bcbca9d58cfad2698eeff70be/lib/error_tracker/integrations/phoenix.ex#L56-L63

I'm happy to attempt a PR if we want this change in the project.

**Comment by crbelaus** [comment]
Good catch! Feel free to open a PR so we can attach to those telemetry events.
