### ISSUE TITLE
error-tracker widget for development environment

### ISSUE THREAD

**Issue by zespere** [elixir-error-tracker/error-tracker#77]
error_tracker could have a widget which displays latest errors, such widget would be added to `root.html.heex` layout in development environment.

Functionalities:
- Widget could consist of "Latest" and "All" buttons in top-right corner of a page
- Modal could pop-up whenever an error occurs but phoenix's error page doesn't show-up

First functionality is convenient as the developer could just click or do `Ctrl+e` and look at the latest error(s).

Second one is nice as developer doesn't even need to do anything to see the error and go straight to de-bugging, "Show only app frames" checkbox is really convenient.

I was inspired by vite's error modal:
![vite_widget](https://github.com/user-attachments/assets/7ceb7403-1b83-4a80-8f08-df0ad43a1c36)

If you click outside of the vite's error modal it disappears, that's useful when developer knows about the error and doesn't want to see the modal.

**Comment by crbelaus** [comment]
Thanks for this proposal but this is out of scope for the ErrorTracker. At least for now.

As an alternative you can use the Phoenix server logs and the ErrorTracker dashboard.

**Comment by zespere** [comment]
I'm not yet sure if I want to do it, but what if I wrote it myself?

**Comment by crbelaus** [comment]
> I'm not yet sure if I want to do it, but what if I wrote it myself?

It would be great if you want to go for it @zespere. Someone is writing an ErrorTracker extension that would integrate it with Telegram notifications. Please, if you write an extension please ping us and we may add it in the README so other users of the ErrorTracker know about it.
