### ISSUE TITLE
Ability to disable error tracking in dev?

### ISSUE THREAD

**Issue by sevenseacat** [elixir-error-tracker/error-tracker#81]
The big insert statements when triggering an error in dev can make it hard to see what's actually going on by normal looking at the server logs, and I feel like we might not actually need to use the dashboard in dev to see if an error occurs?

But we need the package installed in dev, otherwise the migrations will cause a compilation error.

So can we have the package installed, but opt out of the error tracking functionality in dev?

**Comment by crbelaus** [comment]
Thanks for the report @sevenseacat, this request makes a lot of sense. Most likely it would be also a good idea to expose a setting that allows users to customize the ErrorTracker log level (or even fully disable logging).

Let me think about the best way of implementing this. In the meantime you may be interested in #79 which allows you to ignore specific errors. You could create a custom ignorer that ignores every error depending on the current application environment.

**Comment by odarriba** [comment]
Hello @sevenseacat !

We are going to release a new version that includes an `enabled` config flag that allows to disable error tracking on specific environments.

You can see the details in #82.

Thanks for reporting the issue! 🚀
