### ISSUE TITLE
Configure default log level

### ISSUE THREAD

**Issue by crbelaus** [elixir-error-tracker/error-tracker#83]
In certain cases the ErrorTracker logs may pollute the application logs and make it harder to find the actual problem. It would be interesting to allow users configure the log level.

For example [Oban](https://hexdocs.pm/oban/Oban.html#t:option/0) allows the following configuration:

```elixir
# config/config.exs
config :my_app, Oban,
  engine: Oban.Engines.Lite,
  queues: [default: 10],
  repo: MyApp.Repo,
  log: false | Logger.level()
```

Setting a logger level would make the ErrorTracker log everything at that level (for example `:debug`). Setting it to `false` would disable the ErrorTracker logging altogether.

**Comment by MSE99** [comment]
Hey! I'd like to help implement this, any idea on where to start ?, also the ecto repo uses the logger and logs queries executed, should we attempt to also suppress those logs if `log: false` was set ?

**Comment by crbelaus** [comment]
We are not going to pursue this at the moment, so I am closing this issue.
