### ISSUE TITLE
Wrong grouping of occurrences?

### ISSUE THREAD

**Issue by jaimeiniesta** [elixir-error-tracker/error-tracker#87]
Hi, I'm using ErrorTracker 0.2.6 and found that error occurrences are being grouped in an unexpected way.

See this error screenshot:

<img width="1274" alt="Captura de pantalla 2024-09-09 a las 15 17 05" src="https://github.com/user-attachments/assets/7b36f375-ce06-49e0-8c6d-7e809f8c3e09">

The error title is:

> (Oban.PerformError) Rocket.Workers.ScreenshotWorker failed with {:error, :timeout} 

but the full message is:

> Rocket.Workers.A11y failed with {:error, :validation_failed}

It looks like all Oban.PerformError are being grouped together. I've seen the different reasons for occurrences of this error:

<img width="732" alt="Captura de pantalla 2024-09-09 a las 15 15 52" src="https://github.com/user-attachments/assets/2bd26c85-13b7-46d7-802e-20dbdfbb89a5">

Is there a way to have them separate? I'd expect different Oban workers and exit reasons to be accounted as independent errors.

**Comment by crbelaus** [comment]
Currently we are generating the error [fingerprint](https://github.com/elixir-error-tracker/error-tracker/blob/0556cdf6ac2016aa96b44731bd6d5c8f2fc29880/lib/error_tracker/schemas/error.ex#L43-L47) using the error kind and source function and line. I believe that the error reason should be also included here as this would group occurrences differently.

**Comment by crbelaus** [comment]
After a deeper investigation I found out that we removed the reason fingerprinting on #19. In certain cases, such as when accessing a non-existing key in a struct, the reason will contain the entire struct so it will change from error to error even though they are still the same error.

I have to think about this as it seems that both options have their tradeoffs.

**Comment by jaimeiniesta** [comment]
Thanks for the explanation guys, I see the trade-offs.

@odarriba I think that the first option is the best, as then I could have these separate errors:

* (Oban.PerformError) Rocket.Workers.ScreenshotWorker failed with {:error, :timeout} 
* (Oban.PerformError) Rocket.Workers.A11y failed with {:error, :validation_failed}

right?

**Comment by odarriba** [comment]
Yes @jaimeiniesta , the only missing part is that if `Rocket.Workers.ScreenshotWorker` can return both `{:error, :timeout}` and other error values, all of them will be on the same error grouping.

This change is under review in #92 .

Also, if you want specific errors being grouped separately, it is best to raise an exception. Those emit the stacktrace and they are grouped correctly.

Please note that this behaviour is due to Oban internals: returning an error tuple is not really an exception, and there is no stack trace :(.

**Comment by jaimeiniesta** [comment]
That sounds right to me, what was weird was to see different workers grouped together.

**Comment by jaimeiniesta** [comment]
> Also, if you want specific errors being grouped separately, it is best to raise an exception.

Or use [manual error tracking](https://hexdocs.pm/error_tracker/getting-started.html#manual-error-tracking) to avoid dealing with Oban's retries.
