### ISSUE TITLE
API tokens should be anonymized/removed in error context

### ISSUE THREAD

**Issue by jaimeiniesta** [elixir-error-tracker/error-tracker#88]
For errors in API requests where authorization is done with a bearer token, this token should be removed or filtered out before saving to DB. For example, in this context:

```
{
  "request.headers": {
    "accept": "application/json, text/plain, */*",
    "authorization": "Bearer 12341234"
  },
  "request.host": "example.com",
  "request.path": "/api/v1/reports"
}
```

I should not be able to see `Bearer 12341234` and instead I'd expect something like `Bearer REMOVED` or no `authorization` details at all.

**Comment by jaimeiniesta** [comment]
Something that would work in my case is some behaviour that I can implement, similar to the Pruner, that would let me review the context before being saved to DB and let me automate modifying it. In my case it would look for `request.headers.authorization` and replace its value with "REMOVED".

**Comment by crbelaus** [comment]
This makes a lot of sense and is definitely on the roadmap. Thanks for reporting this issue @jaimeiniesta
