### ISSUE TITLE
Router conflict with PhoenixAnalytics

### ISSUE THREAD

**Issue by wkirschbaum** [elixir-error-tracker/error-tracker#90]
The following error pops up when used with phoenix analytics
```bash
error: function parse_options/2 imported from both PhoenixAnalytics.Web.Router and ErrorTracker.Web.Router, call is ambiguous
```

Would it be possible to move the function parse_options/2 to another module and not import it?

https://github.com/lalabuy948/PhoenixAnalytics/issues/2

**Comment by crbelaus** [comment]
Thanks for reporting this @wkirschbaum. The `parse_options/2` should be underscored to exclude it from being automatically imported, such like we do for the `__session__/2` function`

This should be fixed in #91
